parameters:
  jobName: ""
  pool: ""
  environment: ""
  azureSubscription: ""

jobs:
- job: ${{ parameters.jobName }}
  displayName: Build ${{ parameters.environment }}
  pool:
    vmImage: ${{ parameters.pool }}
  continueOnError: false
  steps:      
  - task: AzureCLI@1
    displayName: 'Build task'
    inputs:
      azureSubscription: '${{ parameters.azureSubscription }}'
      addSpnToEnvironment: true
      scriptLocation: inlineScript
      inlineScript: "pwsh .ci/Invoke-PipelineTask.ps1 -azureDevOps -build -tfVersion $(tfVersion) -environmentShort ${{ parameters.environment }} -artifactPath '$(Build.ArtifactStagingDirectory)'"
  
  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifact'
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)
      artifactName: '${{ parameters.environment }}'