parameters:
  buildName: ""
  pool: ""
  environment: ""

stages:
- stage: ${{ parameters.buildName }}
  jobs:
  - job: ${{ parameters.buildName }}
    pool:
      vmImage: $(pool)
    steps:
    - task: AzureCLI@1
      displayName: 'Build task'
      inputs:
        azureSubscription: '$(azureSubscription)'
        addSpnToEnvironment: true
        scriptLocation: inlineScript
        inlineScript: "pwsh .ci/Invoke-PipelineTask.ps1 -azureDevOps -build -tfVersion $(tfVersion)"
      env:
        TF_VAR_environmentShort: ${{ parameters.environment }}