parameters:
  deployment: ""
  pool: ""
  environment: ""

jobs:
- deployment: ${{ parameters.deployment }}
  displayName: Build ${{ parameters.environment }}
  pool:
    vmImage: ${{ parameters.pool }}
  continueOnError: false
  steps:
  - checkout: self
    fetchDepth: 1
    displayName: Get sources 
      
  - task: AzureCLI@1
    displayName: 'Build task'
    inputs:
      azureSubscription: '$(azureSubscription)'
      addSpnToEnvironment: true
      scriptLocation: inlineScript
      inlineScript: "pwsh .ci/Invoke-PipelineTask.ps1 -azureDevOps -build -tfVersion $(tfVersion)"
    env:
      TF_VAR_environmentShort: ${{ parameters.environment }}