stages:
- stage: Deploy_uat
  dependsOn: [Build_uat, Build_prod]
  jobs:
    - template: deploy.yml
      parameters:
        deployment: Deploy_uat
        pool: $(pool)
        environment: uat

- stage: Deploy_prod
  dependsOn: [Build_prod, Deploy_uat]
  jobs:
    - template: deploy.yml
      parameters:
        deployment: Deploy_prod
        pool: $(pool)
        environment: prod
