stages:
- stage: Build
  jobs:
  - template: .ci/templates/build.yml
    parameters:
      jobName: Build_dev
      vmImage: $(vmImage)
      environment: dev
      azureSubscription: $(azureSubscription)

  - template: .ci/templates/build.yml
    parameters:
      jobName: Build_qa
      vmImage: $(vmImage)
      environment: qa
      azureSubscription: $(azureSubscription)
      
  - template: .ci/templates/build.yml
    parameters:
      jobName: Build_prod
      vmImage: $(vmImage)
      environment: prod
      azureSubscription: $(azureSubscription)
      
- stage: Deploy_dev
  dependsOn: [Build]
  jobs:
  - template: .ci/templates/deploy.yml
    parameters:
      deployment: Deploy_dev
      vmImage: $(vmImage)
      environment: dev
      azureSubscription: $(azureSubscription)

- stage: Deploy_qa
  dependsOn: [Build, Deploy_dev]
  jobs:
  - template: .ci/templates/deploy.yml
    parameters:
      deployment: Deploy_qa
      vmImage: $(vmImage)
      environment: qa
      azureSubscription: $(azureSubscription)

- stage: Deploy_prod
  dependsOn: [Build, Deploy_qa]
  jobs:
  - template: .ci/templates/deploy.yml
    parameters:
      deployment: Deploy_prod
      vmImage: $(vmImage)
      environment: prod
      azureSubscription: $(azureSubscription)
