variables:
  azureSubscription: "azureRm"
  tfVersion: "0.12.16"
  pool: 'ubuntu-latest'

name: $(Build.BuildId)

trigger:
- uat

stages:
  - template: .ci/templates/build.yml
  - template: .ci/templates/stages.yml