variables:
  azureSubscription: "azureRm"
  tfVersion: "0.12.16"

name: $(Build.BuildId)

trigger:
- master

stages:
  - template: .ci/templates/build.yml
    parameters:
      azureSubscription: $(azureSubscription)
      tfVersion: $(tfVersion)

  - stage: Deploy_uat
    dependsOn: [Build]
    jobs:
      - deployment: Deploy_uat
        pool:
          vmImage: 'Ubuntu-latest'
        
        environment: uat
        strategy:
          runOnce:
            deploy:
              steps:
              - checkout: self
              - task: AzureCLI@1
                displayName: 'Deploy task'
                inputs:
                  azureSubscription: '$(azureSubscription)'
                  addSpnToEnvironment: true
                  scriptLocation: inlineScript
                  inlineScript: "pwsh .ci/Invoke-PipelineTask.ps1 -azureDevOps -deploy  -tfVersion $(tfVersion)"
