variables:
  azureSubscription: "azureRm"
  tfVersion: "0.12.16"
  pool: 'ubuntu-latest'

name: $(Build.BuildId)

trigger:
- master

stages:
- stage: Build
  jobs:
  - template: .ci/templates/build.yml
    parameters:
      jobName: Build_dev
      pool: $(pool)
      environment: dev
      azureSubscription: $(azureSubscription)
  - template: .ci/templates/build.yml
    parameters:
      jobName: Build_qa
      pool: $(pool)
      environment: qa
      azureSubscription: $(azureSubscription)
  - template: .ci/templates/build.yml
    parameters:
      jobName: Build_prod
      pool: $(pool)
      environment: prod
      azureSubscription: $(azureSubscription)
      
- stage: Deploy_dev
  dependsOn: [Build]
  jobs:
  - template: .ci/templates/deploy.yml
    parameters:
      deployment: Deploy_dev
      pool: $(pool)
      environment: dev
      azureSubscription: $(azureSubscription)

- stage: Deploy_qa
  dependsOn: [Build, Deploy_dev]
  jobs:
  - template: .ci/templates/deploy.yml
    parameters:
      deployment: Deploy_qa
      pool: $(pool)
      environment: qa
      azureSubscription: $(azureSubscription)

- stage: Deploy_prod
  dependsOn: [Build, Deploy_qa]
  jobs:
  - template: .ci/templates/deploy.yml
    parameters:
      deployment: Deploy_prod
      pool: $(pool)
      environment: prod
      azureSubscription: $(azureSubscription)
