variables:
  azureSubscription: "azureRm"
  tfVersion: "0.12.16"
  pool: 'ubuntu-latest'

name: $(Build.BuildId)

trigger:
- uat

stages:
- stage: Build
  jobs:
  - template: .ci/templates/build.yml
    parameters:
      jobName: Build_uat
      pool: $(pool)
      environment: uat
  - template: .ci/templates/build.yml
    parameters:
      jobName: Build_prod
      pool: $(pool)
      environment: prod
      
- stage: Deploy_uat
  dependsOn: [Build, Build_prod]
  jobs:
  - template: .ci/templates/deploy.yml
    parameters:
      deployment: Deploy_uat
      pool: $(pool)
      environment: uat

- stage: Deploy_prod
  dependsOn: [Build, Deploy_uat]
  jobs:
  - template: .ci/templates/deploy.yml
    parameters:
      deployment: Deploy_prod
      pool: $(pool)
      environment: prod
