variables:
  azureSubscription: "azureRm"
  tfVersion: "0.12.16"
  pool: 'ubuntu-latest'

name: $(Build.BuildId)

trigger:
- master

stages:
- stage: Build
  jobs:
  - template: .ci/templates/build.yml
    parameters:
      jobName: Build_dev
      pool: $(pool)
      environment: dev
  - template: .ci/templates/build.yml
    parameters:
      jobName: Build_qa
      pool: $(pool)
      environment: qa
  - template: .ci/templates/build.yml
    parameters:
      jobName: Build_prod
      pool: $(pool)
      environment: prod
      
- stage: Deploy_dev
  dependsOn: [Build]
  jobs:
  - template: .ci/templates/deploy.yml
    parameters:
      deployment: Deploy_dev
      pool: $(pool)
      environment: dev

- stage: Deploy_qa
  dependsOn: [Build, Deploy_dev]
  jobs:
  - template: .ci/templates/deploy.yml
    parameters:
      deployment: Deploy_qa
      pool: $(pool)
      environment: qa

- stage: Deploy_prod
  dependsOn: [Build, Deploy_qa]
  jobs:
  - template: .ci/templates/deploy.yml
    parameters:
      deployment: Deploy_prod
      pool: $(pool)
      environment: prod
