variables:
  - group: terraform-encryption
  - name: devEnvEnabled
    value: true
  - name: qaEnvEnabled
    value: true
  - name: prodEnvEnabled
    value: true
  - name: tfVersion
    value: "0.12.24"
  - name: vmImage
    value: "ubuntu-latest"
  - name: tfFolderName
    value: "tf-asc"

name: $(Build.BuildId)

trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - tf-asc

stages:
  - template: templates/pipeline.yml
