variables:
  azureSubscription: 'azureRm'
  tfVersion: "0.12.16"
  vmImage: 'ubuntu-latest'
  tfFolderName: 'tf-boilerplate'

name: $(Build.BuildId)

trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - tf-boilerplate

stages:
  - template: templates/pipeline.yml
